export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'

export const FETCH_HISTORY_REQUEST = 'FETCH_HISTORY_REQUEST'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE'
export const UPDATE_HISTORY_LIMIT = 'UPDATE_HISTORY_LIMIT'
